[package]
name = "option_result_component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.36.0", default-features = false, features = ["macros"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
