wit_bindgen::generate!({
    path: "wit/component.wit",
    exports: {
        "test:guest/exports": Exports
    }
});

struct Exports;

impl exports::test::guest::exports::Guest for Exports {
    fn get_complex_data() -> exports::test::guest::exports::ComplexData {
        exports::test::guest::exports::ComplexData {
            id: 42,
            name: "Complex Data Example".to_string(),
            values: vec![1.1, 2.2, 3.3, 4.4],
            metadata: Some("Generated by guest component".to_string()),
            status: Ok("Success".to_string()),
        }
    }
}