[package]
name = "complex_return_component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.16.0"

# Empty workspace to prevent this from being part of parent workspace
[workspace]